/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ns.calcbn;


/**
 *
 * @author bishal
 */
public class CalcBN extends javax.swing.JFrame {
    
    private String num1 = "";
    private String num2 = "";
    private String result = "";
    private String opr = "";

    /**
     * Creates new form CalcGUI
     */
    public CalcBN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpButtons = new javax.swing.JDesktopPane();
        btnDel = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnExp = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        lblDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDel.setText("DEL");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnClr.setText("CLR");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });

        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnPercent.setText("%");
        btnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentActionPerformed(evt);
            }
        });

        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnPi.setText("PI");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        btnSin.setText("Sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnLog.setText("Log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnExp.setText("Exp");
        btnExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpActionPerformed(evt);
            }
        });

        btnTan.setText("Tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnCos.setText("Cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        dpButtons.setLayer(btnDel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnFive, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnNine, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnEight, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnSeven, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnClr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnSix, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnThree, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnDot, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnZero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnPercent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnTwo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnOne, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnFour, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnMinus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnPlus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnMultiply, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnDivide, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnEqual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnPi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnSin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnLog, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnExp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnTan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dpButtons.setLayer(btnCos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpButtonsLayout = new javax.swing.GroupLayout(dpButtons);
        dpButtons.setLayout(dpButtonsLayout);
        dpButtonsLayout.setHorizontalGroup(
            dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpButtonsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpButtonsLayout.createSequentialGroup()
                        .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(dpButtonsLayout.createSequentialGroup()
                        .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        dpButtonsLayout.setVerticalGroup(
            dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpButtonsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlus)
                    .addComponent(btnSin)
                    .addComponent(btnPi)
                    .addComponent(btnClr)
                    .addComponent(btnDel))
                .addGap(27, 27, 27)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeven)
                    .addComponent(btnEight)
                    .addComponent(btnNine)
                    .addComponent(btnCos)
                    .addComponent(btnMinus))
                .addGap(27, 27, 27)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFour)
                    .addComponent(btnFive)
                    .addComponent(btnSix)
                    .addComponent(btnTan)
                    .addComponent(btnMultiply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOne)
                    .addComponent(btnTwo)
                    .addComponent(btnDivide)
                    .addComponent(btnExp)
                    .addComponent(btnThree))
                .addGap(27, 27, 27)
                .addGroup(dpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPercent)
                    .addComponent(btnZero)
                    .addComponent(btnLog)
                    .addComponent(btnDot)
                    .addComponent(btnEqual))
                .addGap(30, 30, 30))
        );

        lblDisplay.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        lblDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dpButtons))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayResult() throws Exception{
        switch(opr){
            case "+" :
                result = String.valueOf(Double.parseDouble(num1) + Double.parseDouble(num2));
                break;
            case "-":
                result = String.valueOf(Double.parseDouble(num1) - Double.parseDouble(num2));
                break;
                       
            case "*":
                result = String.valueOf(Double.parseDouble(num1) * Double.parseDouble(num2));
                break;
            case "/":
                result = String.valueOf(Double.parseDouble(num1) / Double.parseDouble(num2));
                break;
                       
            case "SIN":
                result = String.valueOf(java.lang.Math.sin(Double.parseDouble(num2)) * Double.parseDouble(num1));
                break;
                
            case "COS":
                result = String.valueOf(java.lang.Math.cos(Double.parseDouble(num2)) * Double.parseDouble(num1));
                break;
                
            case "TAN":
                result = String.valueOf(java.lang.Math.tan(Double.parseDouble(num2)) * Double.parseDouble(num1));
                break;
                
            case "LOG":
                result = String.valueOf(java.lang.Math.log(Double.parseDouble(num2)) * Double.parseDouble(num1));
                break;
                
            case "EXP":
                result = String.valueOf(java.lang.Math.exp(Double.parseDouble(num2)) * Double.parseDouble(num1));
                break;
        }
        lblDisplay.setText(result);
        num1 = result;
        opr = "";
    }
    
    private void setNums(String op){
        
        num1 = lblDisplay.getText();
        lblDisplay.setText(lblDisplay.getText() + " " + op + " ");
    }
    
    private void doMath(String mth){
        
        if(lblDisplay.getText().isEmpty()){
            num1 = "1";
            lblDisplay.setText(num1 + " * " + mth + " ");
        }
        else{
            num1 = lblDisplay.getText();
            lblDisplay.setText(lblDisplay.getText() + " * " + mth + " ");
//            System.out.println("num1 = " + num1);
//            if(!opr.isEmpty()){
//                lblDisplay.setText(lblDisplay.getText()  + "   " + mth + " ");
//            }
//            else{
//                lblDisplay.setText(lblDisplay.getText() + " * " + mth + " ");
//            }
            
        }   
        
    }
    
    private void getOperand(){
        
        switch(opr){
            case "+":
            case "-":
            case "*":
            case "/":
                try{
                    num2 = lblDisplay.getText().substring(num1.length() + 3);
                }
                catch(Exception e){
                    lblDisplay.setText("");
                }
                break;
                       
            case "SIN":
            case "COS":
            case "TAN":
            case "LOG":
            case "EXP":
                try{
                    num2 = lblDisplay.getText().substring(num1.length() + 7);
                }
                catch(Exception e){
                    lblDisplay.setText("");
                }
                
                break;
        }
    }
    
    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText("");
        opr = "";
    }//GEN-LAST:event_btnClrActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "8");
        
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        // TODO add your handling code here:
        
        if(lblDisplay.getText().isEmpty()){
            lblDisplay.setText(String.valueOf(java.lang.Math.PI));
        }
        else{
            lblDisplay.setText(String.valueOf(java.lang.Math.PI * Double.parseDouble(lblDisplay.getText())));
        }
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        
        if(! lblDisplay.getText().isBlank()){
            lblDisplay.setText(lblDisplay.getText().substring(0, lblDisplay.getText().length()-1));
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        // TODO add your handling code here:
        
        doMath("sin");
        opr = "SIN";
//        if(opr.isEmpty()){
//            opr = "SIN";
//            doMath("sin");
//            System.out.print("if condition");
//        }
//        else{
//            if(num1.isEmpty()){
//                num1 = lblDisplay.getText();
//                System.out.print("second if condition");
//            }
//            else{
//                num1 = lblDisplay.getText();
//                String nums[] = num1.split(" ");
//                num1 = nums[0];
//                num2 = "0";
//                System.out.print(num1);
//
//                try{
//                    System.out.print(lblDisplay.getText());
//                    displayResult(); 
//                    System.out.print("try condition");
//                }
//                catch(Exception e){
//                    lblDisplay.setText("");
//                    System.out.print("catch condition" + e);
//                }
//                doMath("sin");
//                opr = "SIN";
//            }
//        }
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "7");
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "9");
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "4");
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "5");
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "6");
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "1");
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "2");
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "3");
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + "0");
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        // TODO add your handling code here:
        
        lblDisplay.setText(lblDisplay.getText() + ".");
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // TODO add your handling code here:
        
        doMath("cos");
        opr = "COS";
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        // TODO add your handling code here:
        
        doMath("tan");
        opr = "TAN";
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpActionPerformed
        // TODO add your handling code here:
        
        doMath("exp");
        opr = "EXP";
    }//GEN-LAST:event_btnExpActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        
        doMath("log");
        opr = "LOG";
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentActionPerformed
        // TODO add your handling code here:
        try {
            if(! lblDisplay.getText().isEmpty()){
            lblDisplay.setText(String.valueOf(Double.parseDouble(lblDisplay.getText())/100));
            }
        }
        catch(Exception e){
            lblDisplay.setText("");
        }
        
        
    }//GEN-LAST:event_btnPercentActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
        
        if(opr.isEmpty()){
            opr = "+";
            setNums("+");
        }
        else{
            if(num1.isEmpty()){
                num1 = lblDisplay.getText();
            }
            else{
                getOperand();

                try{
                    displayResult(); 
                }
                catch(Exception e){
                    lblDisplay.setText("");
                }
                setNums("+");
                opr = "+";
            }
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        
        if(opr.isEmpty()){
            opr = "-";
            setNums("-");
        }
        else{
            if(num1.isEmpty()){
                num1 = lblDisplay.getText();
            }
            else{
                getOperand();

                try{
                    displayResult(); 
                }
                catch(Exception e){
                    lblDisplay.setText("");
                }
                setNums("-");
                opr = "-";
            }
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
        
        if(opr.isEmpty()){
            opr = "*";
            setNums("*");
        }
        else{
            if(num1.isEmpty()){
                num1 = lblDisplay.getText();
            }
            else{
                getOperand();

                try{
                    displayResult(); 
                }
                catch(Exception e){
                    lblDisplay.setText("");
                }
                setNums("*");
                opr = "*";
            }
        }
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
        
        if(opr.isEmpty()){
            opr = "/";
            setNums("/");
        }
        else{
            if(num1.isEmpty()){
                num1 = lblDisplay.getText();
            }
            else{
                getOperand();

                try{
                    displayResult(); 
                }
                catch(Exception e){
                    lblDisplay.setText("");
                }
                setNums("/");
                opr = "/";
            }
        }
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        
        if(num1.isEmpty()){
            num1 = lblDisplay.getText();
        }
        else{
            
            getOperand();
        }
        try{
           displayResult(); 
        }
        catch(Exception e){
            lblDisplay.setText("Error");
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcBN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcBN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnExp;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JDesktopPane dpButtons;
    private javax.swing.JLabel lblDisplay;
    // End of variables declaration//GEN-END:variables
}
